# General
name: mistersmith
build: develop
paths:
  build: build
  data: data
  images: images
  layouts: layouts
  pages: pages
  scripts: scripts
  styles: styles

# Awspublish
awspublish:
  region: region
  params:
    Bucket: bucket

# Autoprefixer
autoprefixer:
  browsers:
    - last 2 versions

# Browsersync
browsersync:
  server: 'build'
  port: 3100
  notify: false
  ui:
    port: 3101

# Ghpages
ghpages:
  basedir: /mistersmith

# Imagemin
imagemin:
  progressive: true
  interlaced: true

# Markdown
markdown:
  gfm: true

# Sass
sass:
  precision: 7

# Minifycss
minifycss:
  debug: false

# Nunjucks
nunjucks:
  autoescape: false
  watch: false
